markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Jonathan Maltz 
url: http://maltzj.github.io
description: Things I wish I someone had told me about software and community 
twitter: maltzj 
github: maltzj 
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
