markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Jonathan Maltz 
url: http://maltzj.github.io
description: Things I wish I someone had told me about software and community 
twitter: maltzj 
github_username: maltzj 
gravatar_url: http://gravatar.com/avatar/c7393b7ba7ec9c8890dd77d209fbb3c9 
